# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      pg:
        image: postgres  # Docker Hub image
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: eralchemy-test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/eralchemy-test

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Setup postgres test schema
      run: |
        sudo -u postgres psql ${DATABASE_URL} -c "CREATE SCHEMA test;"

    - name: Install graphviz 
      run: |
        sudo apt-get -qq install graphviz libgraphviz-dev

    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: Run tox
      run: |
        tox
